default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: root
  password: root
  pool: 5

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: production
